name: producer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact content
        run: |
          mkdir -p data
          echo "SAFE_DATA=$(date)" > data/info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-artifact
          path: data
